version: "2"
services:
  mywpdb:
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMeIfYouWant
  mywp:
    image: wordpress
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    links:
      - mywpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: ChangeMeIfYouWant